language: python
python:
- '3.6'
- '3.7'
- '3.8'
- pypy3
install:
- pip install -e '.[test]'
- pip install pytest coverage python-coveralls
script:
- coverage run -m pytest
after-success:
- coveralls
